import { FormEvent, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ErrorSummary } from '../components/Forms';
import { Notice, PageHeader } from '../components/Layout';
import { api } from '../lib/api';
import type { User } from '../lib/types';
import { normalizeUserId } from '../lib/validation';

export function DeleteUserPage() {
  const navigate = useNavigate(); const [lookupId, setLookupId] = useState(''); const [user, setUser] = useState<User | null>(null); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null); const lookupRef = useRef<HTMLInputElement>(null);
  function reset() { setLookupId(''); setUser(null); setError(null); setSuccess(null); lookupRef.current?.focus(); }
  async function lookup(event: FormEvent) { event.preventDefault(); if (!lookupId.trim()) { setError('User ID is required.'); lookupRef.current?.focus(); return; } try { const result = await api.getUser(lookupId); setUser(result); setLookupId(result.userId); setError(null); setSuccess(null); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to find the user.'); setUser(null); } }
  async function remove() { if (!user) return; try { await api.deleteUser(user.userId, user.version); setSuccess(`${user.userId} was deleted successfully.`); setUser(null); setLookupId(''); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to delete the user.'); } }
  return <div className="content"><PageHeader title="Delete user" description={user ? 'Confirm the returned user before permanently removing the account.' : 'Enter a user ID to review it before deletion.'} /><section className="card"><div className="cardhead"><h2>{user ? 'Deletion confirmation' : 'Find user'}</h2><span className="sub">Program COUSR03C</span></div><div className="cardbody"><ErrorSummary message={error} focus />{success && <Notice kind="success">{success}</Notice>}{!user ? <form onSubmit={lookup} className="lookup-form" noValidate><div className="field"><label htmlFor="deleteLookup">User ID</label><input ref={lookupRef} id="deleteLookup" value={lookupId} onChange={(event) => setLookupId(normalizeUserId(event.target.value))} autoFocus /><div className="hint">Submitted in uppercase</div></div><button className="btn primary">Find user</button></form> : <><Notice>User found. Review the non-password details before deleting.</Notice><div className="dangerzone"><h2>Permanently delete this user?</h2><p className="sub">This action cannot be undone.</p><dl className="summary"><div><dt>User ID</dt><dd>{user.userId}</dd></div><div><dt>Name</dt><dd>{user.firstName} {user.lastName}</dd></div><div><dt>User type</dt><dd>{user.role === 'ADMIN' ? 'Administrator' : 'Standard user'}</dd></div></dl></div><div className="actions inline-actions"><button className="btn" onClick={reset}>Cancel</button><button className="btn danger" onClick={remove}>Confirm delete</button></div></>}</div>{!user && <div className="actions"><button className="btn" onClick={() => navigate('/admin')}>Back</button><button className="btn" onClick={reset}>Clear</button></div>}</section></div>;
}
