spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  h2:
    console:
      enabled: false
  flyway:
    enabled: true
carddemo:
  seed:
    enabled: false
